# Модуль numpy
Это мощный пакет по работе с многомерными массивами, созданный как инстремент для научных расчетов.

Документация [здесь](https://numpy.org/doc/stable/reference/index.html).

In [1]:
import numpy as np

## Константы

Доступные [константы](https://numpy.org/devdocs/reference/constants.html).

#### numpy.newaxis - Удобный псевдоним для отсутствующей оси. Крайне полезен при индексировании массивов.

## N-мерный массив (ndarray)

### Создание

#### С помощью numpy.array(object, dtype=None, ...)

dtype можно посмотреть [здесь](https://numpy.org/devdocs/user/basics.types.html).

In [2]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x)

[[1 2 3]
 [4 5 6]]


In [3]:
type(x)

numpy.ndarray

In [4]:
x = np.array([[1., 2, 3], [4, 5, 6]])
print(x)

[[1. 2. 3.]
 [4. 5. 6.]]


In [5]:
x = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float)
print(x)

AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

#### С помощью numpy.zeros((axe1, axe2, ...), dtype) - массив заполненый нулями

In [6]:
x = np.zeros((5, 3), dtype=np.float)
print(x)

AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

#### С помощью numpy.ones((rows,columns), dtype) - массив заполненый единицами

In [7]:
x = np.ones((5, 3), dtype=np.int)
print(x)

AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

#### С помощью numpy.eye(rows, dtype) - единичная матрица

In [8]:
x = np.eye(5, dtype=np.int)
print(x)

AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

#### С помощью numpy.empty((rows,columns)) - массив заполненый "мусором"

In [9]:
x = np.empty((5, 3), dtype=np.float)
print(x)

AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

#### С помощью numpy.arange(start, stop, step) - создает массив, значения которого находятся в диапазоне от start до stop с шагом step

In [10]:
x = np.arange(0, 10, 1/3)
print(x)

[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667
 2.         2.33333333 2.66666667 3.         3.33333333 3.66666667
 4.         4.33333333 4.66666667 5.         5.33333333 5.66666667
 6.         6.33333333 6.66666667 7.         7.33333333 7.66666667
 8.         8.33333333 8.66666667 9.         9.33333333 9.66666667]


#### С помощью numpy.linspace(start, stop, num_of_elements) - создает массив с количеством элементов равным num_of_elements, значения находятся в диапазоне от start до stop

In [11]:
x = np.linspace(0, 0.9, 10)
print(x)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


#### С помощью numpy.logspace() - аналогично linspace, но значения элементов нахотятся в пределах логарифмической шкалы

In [12]:
x = np.logspace(0, 9, 10)
print(x)

[1.e+00 1.e+01 1.e+02 1.e+03 1.e+04 1.e+05 1.e+06 1.e+07 1.e+08 1.e+09]


### Обращение к элементам

In [13]:
x = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(x)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [14]:
x[1]

array([[5, 6],
       [7, 8]])

In [15]:
x[-1]

array([[5, 6],
       [7, 8]])

In [16]:
x[0, 0]

array([1, 2])

In [17]:
x[0, 0, 0]

1

In [18]:
indexes = np.array([1,0])
x[indexes]

array([[[5, 6],
        [7, 8]],

       [[1, 2],
        [3, 4]]])

In [19]:
x[::-1]

array([[[5, 6],
        [7, 8]],

       [[1, 2],
        [3, 4]]])

In [20]:
x[::-1, ::-1]

array([[[7, 8],
        [5, 6]],

       [[3, 4],
        [1, 2]]])

In [21]:
x[::-1, ::-1, ::-1]

array([[[8, 7],
        [6, 5]],

       [[4, 3],
        [2, 1]]])

### Атрибуты

Полный список атрибутов [здесь](https://numpy.org/devdocs/reference/arrays.ndarray.html#array-attributes).

In [22]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(x)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


#### obj.ndim - количество измерений массива 

In [23]:
x.ndim

2

#### obj.shape - размеры массива

In [24]:
x.shape

(4, 3)

#### obj.size - общее количество элементов в массиве

In [25]:
x.size

12

#### obj.dtype - тип элементов в массиве

In [26]:
x.dtype

dtype('int32')

#### obj.itemsize - размер элемента

In [27]:
x.itemsize

4

#### obj.data - буфер с элементами массива

In [28]:
x.data

#### obj.flat - одномерный итератор по элементам массива

In [29]:
for element in x.flat:
    print(element)

1
2
3
4
5
6
7
8
9
10
11
12


#### obj.T - транспонированный массив

In [30]:
x.T

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [31]:
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

#### obj.real - действительная часть

In [32]:
x.real

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

#### obj.imag - мнимая часть

In [33]:
x.imag

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

### Методы управления формой

#### obj.reshape(shape[, order]) - возвращает массив с новой формой

In [34]:
a = np.linspace(1, 12, 12)
print(a)
b = a.reshape((3, 4))
print(b)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]


In [35]:
a = np.array([[1, 2, 3], [-4, 5, 6], [77, 8, 9], [10, 11, 12]])
print(a)
b = a.reshape((3, 4))
print(b)

[[ 1  2  3]
 [-4  5  6]
 [77  8  9]
 [10 11 12]]
[[ 1  2  3 -4]
 [ 5  6 77  8]
 [ 9 10 11 12]]


In [36]:
a = np.array([[1, 2, 3], [-4, 5, 6], [77, 8, 9], [10, 11, 12]])
print(a)
b = a.reshape((3, 4), order='C')
print(b)

[[ 1  2  3]
 [-4  5  6]
 [77  8  9]
 [10 11 12]]
[[ 1  2  3 -4]
 [ 5  6 77  8]
 [ 9 10 11 12]]


In [37]:
a = np.array([[1, 2, 3], [-4, 5, 6], [77, 8, 9], [10, 11, 12]])
print(a)
b = a.reshape((3, 4), order='F')
print(b)

[[ 1  2  3]
 [-4  5  6]
 [77  8  9]
 [10 11 12]]
[[ 1 10  8  6]
 [-4  2 11  9]
 [77  5  3 12]]


In [38]:
b = a.reshape((3, 3))
print(b)

ValueError: cannot reshape array of size 12 into shape (3,3)

#### obj.resize(new_shape) - меняет массив в соответствии с новыми размером и формой

In [109]:
a = np.array([[1, 2, 3], [-4, 5, 6], [77, 8, 9], [10, 11, 12]])
print(a)
a.resize((3, 4))
print(a)

[[ 1  2  3]
 [-4  5  6]
 [77  8  9]
 [10 11 12]]
[[ 1  2  3 -4]
 [ 5  6 77  8]
 [ 9 10 11 12]]


In [112]:
a.resize((4, 2))
print(a)

[[ 1  2]
 [ 3 -4]
 [ 5  6]
 [77  8]]


#### obj.transpose(*axes) - транспонирует массив

In [117]:
a = np.arange(24).reshape([2, 3, 4])
print(a)
b = a.transpose()
print(b)
print("",a.shape, b.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[ 0 12]
  [ 4 16]
  [ 8 20]]

 [[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]]
 (2, 3, 4) (4, 3, 2)


In [118]:
b[0,2,1]

20

In [119]:
a[1,2,0] 

20

In [122]:
b = a.transpose(0, 1, 2)
print(b)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [123]:
b = a.transpose(1, 0, 2)
print(b)

[[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]


In [124]:
print(a[0,1,2],b[1,0,2])

6 6


#### ndarray.swapaxes(axis1, axis2) - возвращает массив с помененными местами осями

In [129]:
a = np.arange(24). reshape(2,3,4)
print(a)
b = a.swapaxes(0, 2)
print(b)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[ 0 12]
  [ 4 16]
  [ 8 20]]

 [[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]]


In [132]:
a[0, 1, 2] == b[2, 1, 0]

True

In [133]:
a[1, 1, 0] == b[1, 1, 0]

False

#### obj.flatten([order]) - возвращает одномерный массив всех элементов

In [135]:
a = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(a)
b = a.flatten()
print(b,type(b))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[1 2 3 4 5 6 7 8] <class 'numpy.ndarray'>


In [136]:
a = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(a)
b = a.flatten(order='C')
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[1 2 3 4 5 6 7 8]


In [137]:
a = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(a)
b = a.flatten(order='F')
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[1 5 3 7 2 6 4 8]


### Вычислительные методы

Полный список методов [здесь](https://numpy.org/devdocs/reference/arrays.ndarray.html#array-methods).

In [138]:
x = np.array([[1, 2, 3], [-4, 5, 6], [77, 8, 9], [10, 11, 12]])
print(x)

[[ 1  2  3]
 [-4  5  6]
 [77  8  9]
 [10 11 12]]


#### obj.max() - значение максимального элемента

In [139]:
x.max()

77

In [140]:
x.max(0)

array([77, 11, 12])

In [141]:
x.max(1)

array([ 3,  6, 77, 12])

#### obj.argmax() - индекс максимального элемента

In [142]:
x.argmax()

6

In [146]:
x.argmax(1)

array([2, 2, 0, 2], dtype=int64)

#### obj.min() - значение минимального элемента

In [147]:
x.min()

-4

#### obj.argmin() - индекс минимального элемента

In [148]:
x.argmin()

3

#### obj.sum() - значение суммы элементов

In [149]:
x.sum()

140

In [151]:
print(x)
x.sum(1)

[[ 1  2  3]
 [-4  5  6]
 [77  8  9]
 [10 11 12]]


array([ 6,  7, 94, 33])

#### obj.cumsum() - значение кумулятивной суммы

In [152]:
print(x)
x.cumsum()

[[ 1  2  3]
 [-4  5  6]
 [77  8  9]
 [10 11 12]]


array([  1,   3,   6,   2,   7,  13,  90,  98, 107, 117, 128, 140])

In [153]:
x.cumsum(1)

array([[ 1,  3,  6],
       [-4,  1,  7],
       [77, 85, 94],
       [10, 21, 33]])

#### obj.mean() - среднее арифметическое

In [154]:
x.mean()

11.666666666666666

#### obj.var() - дисперсия

In [155]:
x.var()

408.05555555555543

#### obj.std() - стандартное отклонение

In [156]:
x.std()

20.200385034834248

#### obj.all() - True, если все элементы True

In [160]:
print(x)
x[0, 0] = 1
x.all()

[[ 0  2  3]
 [-4  5  6]
 [77  8  9]
 [10 11 12]]


True

#### obj.any() - True, если один из элементов True

In [161]:
x.any()

True

### Прочие методы

#### obj.tolist() - Возвращает ndim-уровневый список списков

In [162]:
a = x.tolist()
print(a)
print(type(a))

[[1, 2, 3], [-4, 5, 6], [77, 8, 9], [10, 11, 12]]
<class 'list'>


#### obj.fill(value) - заполняет массив заданным значением

In [163]:
x.fill(5)
print(x)

[[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]


In [167]:
x = np.array([[1, 2, 3], [-4, 5, 6], [77, 8, 9], [10, 11, 12]])
y = np.ones((4, 3), dtype=np.int) * 5
x == y

AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

## Операции
Возможно применение любой арифметичесткой операции (+, -, *, /, //, %, divmod(), ** or pow(), <<, >>, &, ^, |, ~) и операций сравнения (==, <, >, <=, >=, !=) 

In [168]:
x = np.array([[3, 2, 1], [4, 5, 6]])
y = np.array([[9, 2, 7], [10, 11, 12]])

In [169]:
x + y

array([[12,  4,  8],
       [14, 16, 18]])

In [170]:
x + 3

array([[6, 5, 4],
       [7, 8, 9]])

In [ ]:
x * y

In [ ]:
x / y

In [ ]:
y // x

In [ ]:
y % x

In [ ]:
divmod(y, x)

In [ ]:
np.any(y == x)

In [ ]:
y >= x

In [ ]:
y < x

Полученные значения можно сохранять

In [ ]:
z = y ** x
print(z)

# Функции numpy

Их настолько много, что проще посмотреть документацию

#### Сортировка

In [ ]:
a = np.array([[7, 2, 3], [3, 9, 6], [1, 8, 4]])
b = np.sort(a)
print(b)

In [ ]:
a = np.array([[7, 2, 3], [3, 9, 6], [1, 8, 4]])
b = np.sort(a, axis=0)
print(b)

#### Генерация вектора случайных чисел с равномерным распределением

In [ ]:
x = np.random.uniform(0, 1, 200)
print(x.reshape(20, 10))

In [ ]:
x = np.random.randn(30)
print(x)

#### Генерация вектора случайных чисел с нормальным распределением

In [ ]:
x = np.random.normal(0, 1, 1000)
y = x * 3 + 5
#print(y)
print(y.mean(), y.std())

#### Генерация двумерного массива случайных чисел с стандартным нормальным распределением

In [ ]:
x = np.random.randn(600, 2)
print(x)

In [ ]:
import matplotlib.pyplot as plt
plt.scatter(x[:, 0], x[:, 1])

#### Объединение массивов

In [ ]:
a = np.array([[1, 2], [3, 4], [5, 6]])
b = np.array([[7, 8], [9, 0], [1, 2]])
print(a, b, sep='\n')

In [ ]:
np.hstack((a, b))

In [ ]:
np.vstack((a, b))

In [ ]:
np.concatenate((a, b))

In [ ]:
np.concatenate((a, b), axis = 1)

In [ ]:
np.stack((a, b))

#### Перестановки и перемешивание

In [ ]:
np.random.permutation(10)

In [ ]:
a = np.array([1, 6, 2, 8])
b = np.random.permutation(a)
print(a)
print(b)

In [ ]:
a = np.array([[0, 1], [2, 3], [4, 5], [6, 7], [8, 9]])
b = np.random.permutation(a)
print(a)
print(b)

In [ ]:
a = np.arange(10)
print(a)
np.random.shuffle(a)
print(a)

In [ ]:
a = np.arange(10).reshape(5, 2)
print(a)
np.random.shuffle(a)
print(a)